module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class', // or 'media'
  theme: {
    extend: {
      colors: {
        primary: 'var(--tena-primary)',
        secondary: 'var(--tena-secondary)',
        neutral: 'var(--tena-neutral)',
        surface: 'var(--tena-surface)',
        'primary-text': 'var(--tena-text)',
        'secondary-text': 'var(--tena-muted)',
        'border-color': 'var(--tena-border)',
        gray: {
          50: 'var(--tena-surface)',
          100: 'var(--tena-surface-soft)',
          200: 'var(--tena-surface-strong)',
          300: 'var(--tena-border)',
          400: 'var(--tena-border-strong)',
          500: 'var(--tena-muted-soft)',
          600: 'var(--tena-muted)',
          700: 'var(--tena-muted-strong)',
          800: 'var(--tena-text)',
          900: 'var(--tena-text)',
        },
        slate: {
          50: 'var(--tena-surface)',
          100: 'var(--tena-surface-soft)',
          200: 'var(--tena-surface-strong)',
          300: 'var(--tena-border)',
          400: 'var(--tena-border-strong)',
          500: 'var(--tena-muted-soft)',
          600: 'var(--tena-muted)',
          700: 'var(--tena-muted-strong)',
          800: 'var(--tena-text)',
          900: 'var(--tena-text)',
        },
        blue: {
          50: 'rgba(var(--tena-primary-rgb), 0.08)',
          100: 'rgba(var(--tena-primary-rgb), 0.12)',
          200: 'rgba(var(--tena-primary-rgb), 0.2)',
          300: 'rgba(var(--tena-primary-rgb), 0.35)',
          400: 'rgba(var(--tena-primary-rgb), 0.5)',
          500: 'var(--tena-primary)',
          600: 'var(--tena-primary)',
          700: 'var(--tena-primary)',
          800: 'var(--tena-primary)',
          900: 'var(--tena-primary)',
        },
        emerald: {
          50: 'rgba(var(--tena-secondary-rgb), 0.1)',
          100: 'rgba(var(--tena-secondary-rgb), 0.14)',
          200: 'rgba(var(--tena-secondary-rgb), 0.2)',
          300: 'rgba(var(--tena-secondary-rgb), 0.32)',
          400: 'rgba(var(--tena-secondary-rgb), 0.45)',
          500: 'var(--tena-secondary)',
          600: 'var(--tena-secondary)',
          700: 'var(--tena-secondary)',
          800: 'var(--tena-secondary)',
          900: 'var(--tena-secondary)',
        },
        green: {
          50: 'rgba(var(--tena-secondary-rgb), 0.1)',
          100: 'rgba(var(--tena-secondary-rgb), 0.14)',
          200: 'rgba(var(--tena-secondary-rgb), 0.2)',
          300: 'rgba(var(--tena-secondary-rgb), 0.32)',
          400: 'rgba(var(--tena-secondary-rgb), 0.45)',
          500: 'var(--tena-secondary)',
          600: 'var(--tena-secondary)',
          700: 'var(--tena-secondary)',
          800: 'var(--tena-secondary)',
          900: 'var(--tena-secondary)',
        },
        red: {
          50: 'rgba(var(--tena-danger-rgb), 0.1)',
          100: 'rgba(var(--tena-danger-rgb), 0.16)',
          200: 'rgba(var(--tena-danger-rgb), 0.22)',
          300: 'rgba(var(--tena-danger-rgb), 0.32)',
          400: 'rgba(var(--tena-danger-rgb), 0.45)',
          500: 'var(--tena-danger)',
          600: 'var(--tena-danger)',
          700: 'var(--tena-danger)',
          800: 'var(--tena-danger)',
          900: 'var(--tena-danger)',
        },
        amber: {
          50: 'rgba(var(--tena-warning-rgb), 0.12)',
          100: 'rgba(var(--tena-warning-rgb), 0.18)',
          200: 'rgba(var(--tena-warning-rgb), 0.26)',
          300: 'rgba(var(--tena-warning-rgb), 0.35)',
          400: 'rgba(var(--tena-warning-rgb), 0.45)',
          500: 'var(--tena-warning)',
          600: 'var(--tena-warning)',
          700: 'var(--tena-warning)',
          800: 'var(--tena-warning)',
          900: 'var(--tena-warning)',
        },
        yellow: {
          50: 'rgba(var(--tena-warning-rgb), 0.12)',
          100: 'rgba(var(--tena-warning-rgb), 0.18)',
          200: 'rgba(var(--tena-warning-rgb), 0.26)',
          300: 'rgba(var(--tena-warning-rgb), 0.35)',
          400: 'rgba(var(--tena-warning-rgb), 0.45)',
          500: 'var(--tena-warning)',
          600: 'var(--tena-warning)',
          700: 'var(--tena-warning)',
          800: 'var(--tena-warning)',
          900: 'var(--tena-warning)',
        },
        // Legacy mapping for older components
        facebook: {
          blue: 'var(--tena-primary)',
          gray: 'var(--tena-neutral)',
          white: 'var(--tena-surface)',
        },
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica', 'Arial', 'sans-serif'],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '32px',
        '8': '40px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.08)',
        DEFAULT: '0 1px 2px rgba(0,0,0,0.08), 0 4px 12px rgba(0,0,0,0.06)',
        md: '0 1px 2px rgba(0,0,0,0.08), 0 4px 12px rgba(0,0,0,0.06)',
        lg: '0 1px 2px rgba(0,0,0,0.08), 0 4px 12px rgba(0,0,0,0.06)',
        xl: '0 1px 2px rgba(0,0,0,0.1), 0 6px 20px rgba(0,0,0,0.12)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
