
"""Standardize models with TimestampMixin and ModelMixin

Revision ID: T_021_standardize_models
Revises: T_020_alert_rules_tenant_scope
Create Date: 2023-10-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'T_021_standardize_models'
down_revision = 'T_020_alert_rules_tenant_scope'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add created_at and updated_at to tables that inherit TimestampMixin
    # For each table, add the columns if they don't exist, with appropriate defaults and nullability.

    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # agents
    columns = inspector.get_columns('agents')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('agents', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # modules
    columns = inspector.get_columns('modules')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('modules', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # scheduled_scans
    columns = inspector.get_columns('scheduled_scans')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('scheduled_scans', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # integrity_events
    columns = inspector.get_columns('integrity_events')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # users
    columns = inspector.get_columns('users')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # notifications
    columns = inspector.get_columns('notifications')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # process_snapshots
    columns = inspector.get_columns('process_snapshots')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('process_snapshots', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # tenants
    columns = inspector.get_columns('tenants')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # roles
    columns = inspector.get_columns('roles')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('roles', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # audit_logs
    columns = inspector.get_columns('audit_logs')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # compliance_results
    columns = inspector.get_columns('compliance_results')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # registry_snapshots
    columns = inspector.get_columns('registry_snapshots')
    column_names = [col['name'] for col in columns]
    with op.batch_alter_table('registry_snapshots', schema=None) as batch_op:
        if 'created_at' not in column_names:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))
        if 'updated_at' not in column_names:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("timezone('utc', now())")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove created_at and updated_at from tables that inherit TimestampMixin

    # registry_snapshots
    with op.batch_alter_table('registry_snapshots', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # compliance_results
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # audit_logs
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # roles
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # tenants
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # process_snapshots
    with op.batch_alter_table('process_snapshots', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # notifications
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # users
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # integrity_events
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # scheduled_scans
    with op.batch_alter_table('scheduled_scans', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # modules
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # agents
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
